title: "Akshay Dudhe"
description: "Java Backend Developer | Passionate about scalable and secure application development"
baseurl: "" # Leaveing it empty unless hosting in a subdirectory
url: "https://github.com/akshaydudhe943"
show_downloads: true
theme: jekyll-theme-minimal
