title: "Akshay Dudhe"
description: "Java Backend Developer | Passionate about scalable and secure application development"
baseurl: "" # Leave empty unless hosting in a subdirectory
url: "https://github.com/akshaydudhe943" # Replace with your GitHub Pages URL

# Appearance settings
show_downloads: true

# Contact information (Optional)
email: akshaydudhe943@gmail.com
address: Hinjewadi Phase 1, Pune, Maharashtra, India
phone: +91 7666159449

# Customization
social_links:
  - name: GitHub
    url: https://github.com/akshaydudhe943
    icon: fab fa-github

  - name: LinkedIn
    url: https://www.linkedin.com/in/akshay-dudhe-b51b691b5/
    icon: fab fa-linkedin

# Footer (Optional)
footer_message: "Made with ❤️ by Akshay Dudhe😊"
